<?php

// Configuración de la conexión a la base de datos
$host = 'sql207.infinityfree.com';
$dbname = 'if0_38802651_sigesmancor';
$username = 'if0_38802651';
$password = 'juanarroyo123';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8", $username, $password);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "Conexión exitosa. Iniciando el seeder...\n";
} catch (PDOException $e) {
    die("Error de conexión: " . $e->getMessage());
}

// Función para ejecutar consultas preparadas
function ejecutarConsulta($pdo, $sql, $params = [])
{
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $stmt;
}

// Función para obtener el último ID insertado
function ultimoId($pdo)
{
    return $pdo->lastInsertId();
}

// 1. Poblar tabla categorias_equipos (solo si no existen)
echo "Poblando categorias_equipos...\n";
$categorias = [
    ['Hemodiálisis', 'Equipos para hemodiálisis'],
    ['Diagnóstico', 'Equipos para diagnóstico médico'],
    ['Esterilización', 'Equipos para esterilización'],
    ['Almacenamiento', 'Equipos para almacenamiento'],
    ['Peso', 'Equipos para medición de peso'],
    ['Climatización', 'Equipos para control de temperatura y aire'],
    ['Oxigenación', 'Equipos para suministro de oxígeno'],
    ['Seguridad', 'Equipos para seguridad y emergencias'],
    ['Energía', 'Equipos para gestión de energía'],
    ['Soporte Vital', 'Equipos para soporte vital'],
];

$categoria_ids = [];
foreach ($categorias as $categoria) {
    // Verificar si la categoría ya existe
    $stmt = ejecutarConsulta($pdo, "SELECT id FROM categorias_equipos WHERE nombre = ?", [$categoria[0]]);
    $result = $stmt->fetch(PDO::FETCH_ASSOC);

    if ($result) {
        // Usar ID existente
        $categoria_ids[$categoria[0]] = $result['id'];
        echo "Categoría '{$categoria[0]}' ya existe, usando ID {$result['id']}.\n";
    } else {
        // Insertar nueva categoría
        ejecutarConsulta($pdo, "INSERT INTO categorias_equipos (nombre, descripcion) VALUES (?, ?)", $categoria);
        $categoria_ids[$categoria[0]] = ultimoId($pdo);
        echo "Categoría '{$categoria[0]}' creada con ID {$categoria_ids[$categoria[0]]}.\n";
    }
}

// 2. Poblar tabla equipos
echo "Poblando equipos...\n";
$equipos = [
    [
        $categoria_ids['Hemodiálisis'],
        'D-1',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'FRESENIUS',
        '4008S',
        '0SXAlWS8',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Hemodiálisis'],
        'D-2',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'NIPRO',
        'DIAMAX',
        'J22936S',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Hemodiálisis'],
        'D-7',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'FRESENIUS',
        '4008S',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Hemodiálisis'],
        'D-9',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'FRESENIUS',
        '4008S',
        '1XKA2NS0',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Hemodiálisis'],
        'D-9-2',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'FRESENIUS',
        '4008S',
        '1SXA2JHK',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Hemodiálisis'],
        'D-11',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'FRESENIUS',
        '4008S',
        'ISXA2PFW',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Hemodiálisis'],
        'M-13',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'NIPRO',
        'DIAMAX',
        'J21656S',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Hemodiálisis'],
        'MC-13',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'NIPRO',
        'DIAMAX',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Hemodiálisis'],
        'MS-14',
        'Máquina de Hemodiálisis',
        'hemodiálisis',
        'NIPRO',
        'DIAMAX',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica la sangre para pacientes con insuficiencia renal',
        null,
        'horas'
    ],
    [
        $categoria_ids['Diagnóstico'],
        'BIO-001',
        'Monitor Desfibrilador',
        'desfibrilador',
        'COMEN',
        'S8',
        '58032124015',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Diagnostica y restablece el ritmo cardíaco en paros cardíacos',
        null,
        'horas'
    ],
    [
        $categoria_ids['Diagnóstico'],
        'BIO-002',
        'Electrocardiograma',
        'electrocardiograma',
        'EDAN',
        'SE-3',
        '360250-M2550050030',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Registra señales eléctricas del corazón para detectar afecciones cardíacas',
        null,
        'horas'
    ],
    [
        $categoria_ids['Soporte Vital'],
        'BIO-003',
        'Extractor de Fluidos',
        'extractor',
        null,
        null,
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        null,
        null,
        'horas'
    ],
    [
        $categoria_ids['Soporte Vital'],
        'BIO-004',
        'Resucitador Manual',
        'resucitador',
        null,
        null,
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        null,
        null,
        'horas'
    ],
    [
        $categoria_ids['Diagnóstico'],
        'BIO-005',
        'Pulsómetro-Oxímetro',
        'pulsómetro',
        null,
        null,
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        null,
        null,
        'horas'
    ],
    [
        $categoria_ids['Soporte Vital'],
        'BIO-006',
        'Laringoscopio',
        'laringoscopio',
        null,
        null,
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        null,
        null,
        'horas'
    ],
    [
        $categoria_ids['Diagnóstico'],
        'BIO-007',
        'Glucómetro',
        'glucómetro',
        null,
        null,
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        null,
        null,
        'horas'
    ],
    [
        $categoria_ids['Diagnóstico'],
        'BIO-008',
        'Estetoscopio',
        'estetoscopio',
        'RIESTER',
        '4001-02',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Amplifica ruidos corporales para diagnóstico',
        null,
        'horas'
    ],
    [
        $categoria_ids['Diagnóstico'],
        'BIO-009',
        'Tensiómetro Rodante',
        'tensiómetro',
        'RIESTER',
        'Big Ben',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Mide la presión arterial',
        null,
        'horas'
    ],
    [
        $categoria_ids['Esterilización'],
        'BIO-010',
        'Autoclave-Esterilizador Calor Húmedo',
        'autoclave',
        'LOVIAP',
        'YX-18LDJ',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Utiliza vapor a presión para esterilizar',
        null,
        'horas'
    ],
    [
        $categoria_ids['Almacenamiento'],
        'BIO-011',
        'Refrigeradora',
        'refrigeradora',
        'LG',
        'GT32BPPDC',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Enfría y conserva materiales',
        null,
        'horas'
    ],
    [
        $categoria_ids['Diagnóstico'],
        'BIO-012',
        'Termómetro Digital',
        'termómetro',
        'THERMOMETER',
        'SPE-16',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Controla la temperatura de refrigeradoras',
        null,
        'horas'
    ],
    [
        $categoria_ids['Peso'],
        'BIO-013',
        'Báscula Electrónica',
        'báscula',
        'REY',
        'LP7553',
        'AC2020082505',
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Mide el peso corporal con precisión',
        null,
        'horas'
    ],
    [
        $categoria_ids['Climatización'],
        'BIO-014',
        'Aire Acondicionado',
        'aire acondicionado',
        'YORK',
        'INVERTER',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Enfría o calienta el ambiente',
        null,
        'horas'
    ],
    [
        $categoria_ids['Climatización'],
        'BIO-015',
        'Inyector/Extractor de Aire',
        'ventilador',
        'ADE/HON&GUAN',
        'HF-315P',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Purifica el aire regulando temperatura y oxígeno',
        null,
        'horas'
    ],
    [
        $categoria_ids['Oxigenación'],
        'BIO-016',
        'Balón de Oxígeno Estacionario',
        'oxígeno',
        null,
        '10 m3',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Suministra oxigenoterapia de bajo flujo',
        null,
        'horas'
    ],
    [
        $categoria_ids['Oxigenación'],
        'BIO-017',
        'Balón de Oxígeno Portátil',
        'oxígeno',
        null,
        '10 m3',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Suministra oxigenoterapia de bajo flujo',
        null,
        'horas'
    ],
    [
        $categoria_ids['Seguridad'],
        'BIO-018',
        'Extintor',
        'extintor',
        null,
        'POS-CO2',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Contiene agente extintor para incendios',
        null,
        'horas'
    ],
    [
        $categoria_ids['Diagnóstico'],
        'BIO-019',
        'Reloj e Higro-Termómetro',
        'termómetro',
        'BOEGO',
        'SH-110',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Monitorea temperatura y humedad',
        null,
        'horas'
    ],
    [
        $categoria_ids['Seguridad'],
        'BIO-020',
        'Lámparas de Emergencia',
        'lámpara',
        'OPALUX',
        'Slim Ultrabillante',
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        'Proporciona iluminación en emergencias',
        null,
        'horas'
    ],
    [
        $categoria_ids['Energía'],
        'BIO-021',
        'Grupo Electrógeno',
        'generador',
        null,
        null,
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        null,
        null,
        'horas'
    ],
    [
        $categoria_ids['Energía'],
        'BIO-022',
        'Tablero de Transferencia',
        'tablero',
        null,
        null,
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        null,
        null,
        'horas'
    ],
    [
        $categoria_ids['Energía'],
        'BIO-023',
        'Sistema Eléctrico',
        'sistema eléctrico',
        null,
        null,
        null,
        null,
        null,
        null,
        'activo',
        0,
        0,
        null,
        0,
        0,
        0,
        null,
        null,
        'horas'
    ],
];

foreach ($equipos as $equipo) {
    // Verificar si el equipo ya existe por código
    $stmt = ejecutarConsulta($pdo, "SELECT codigo FROM equipos WHERE codigo = ?", [$equipo[1]]);
    if ($stmt->rowCount() == 0) {
        ejecutarConsulta(
            $pdo,
            "INSERT INTO equipos (categoria_id, codigo, nombre, tipo_equipo, marca, modelo, numero_serie, capacidad, fase, ubicacion, estado, orometro_actual, anterior_orometro, proximo_orometro, limite, notificacion, mantenimiento, observaciones, imagen, tipo_orometro) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            $equipo
        );
        echo "Equipo '{$equipo[2]}' ({$equipo[1]}) insertado.\n";
    } else {
        echo "Equipo con código '{$equipo[1]}' ya existe, omitiendo.\n";
    }
}

echo "\n=== SEEDER COMPLETADO EXITOSAMENTE ===\n";
echo "✅ Categorías procesadas: " . count($categorias) . "\n";
echo "✅ Equipos procesados: " . count($equipos) . "\n";
echo "\n🎉 Nuevos equipos biomédicos agregados a las tablas!\n";
